### ISSUE TITLE
Power distribution

### ISSUE THREAD

**Issue by DEVANSH-DVJ** [Krittika-Astronomy-Club-IITB/Krittika-Website#31]
"Moderators" imply both admins and moderators

Events:
New event by moderators only.
Event deletion by moderators only.

Blogs:
New Post allowed by everyone.
By default - not approved. Can be "approved" and "not approved" by moderators only.
Post deletion by post's author and admin only.
Post editing by author only.
If not approved, 
.... Visible only to moderators. (If others even try to open, redirect them back)
.... All moderators can comment and these would automatically be is_visible = False.
.... is_visible is non-toggle-able
If approved,
.... Visible to all.
.... Everyone can comment, is_visible = True.
..... is_visible is toggle-able by moderators.
Comments can be deleted only by comment's author or moderators.
Comments editing by comment's author only.

Forum:
New Post allowed by everyone.
Post deletion by post's author and moderators only.
Post editing by author and admins only.
Everyone can comment.
Comments can be deleted only by comment's author or moderators.
Comments editing by comment's author only.
Topic
.... New Topic allowed by everyone.
.... By default - not approved. Can be "approved" by moderators only. (Can not be "not approved" else the related posts would have no topic visible.)
.... Topic editing by moderators only.
.... Topic deletion not allowed as then the related posts would have no topic
// Add about archive

// Don't close this issue

**Comment by hrshtv** [comment]
Topic deletion should be allowed.   
Say, the mods create a topic called 'Krittika Summer Projects 2020' for discussions.   
Then, after the completion of KSP 2020, they should be able to delete the topic (Deleting the topic also deletes all the posts in that topic)

**Comment by DEVANSH-DVJ** [comment]
> Topic deletion should be allowed.
> Say, the mods create a topic called 'Krittika Summer Projects 2020' for discussions.
> Then, after the completion of KSP 2020, they should be able to delete the topic (Deleting the topic also deletes all the posts in that topic)
Shouldn't the discussion be kept for future, say maybe, like before the likely announcement of KSP 2021, people may want to know how it went.

> Regarding topic disapproval, if a topic with posts gets disapproved, all the posts associated with it do not get deleted, but they become invisible.
> On re-approval of the topic, they become visible again.
Instead, all the posts can be shown but no new post can be of that topic can be created.
Like, for KSP 2020. It can be made un-approved so no new post would be of KSP 2020.
Having is_archived an alternative to this.

**Comment by DEVANSH-DVJ** [comment]
> Topic deletion should be allowed.
> Say, the mods create a topic called 'Krittika Summer Projects 2020' for discussions.
> Then, after the completion of KSP 2020, they should be able to delete the topic (Deleting the topic also deletes all the posts in that topic)
Shouldn't the discussion be kept for future, say maybe, like before the likely announcement of KSP 2021, people may want to know how it went.

> Regarding topic disapproval, if a topic with posts gets disapproved, all the posts associated with it do not get deleted, but they become invisible.
> On re-approval of the topic, they become visible again.
Instead, all the posts can be shown but no new post can be of that topic can be created.
Like, for KSP 2020. It can be made un-approved so no new post would be of KSP 2020.
Having is_archived an alternative to this.

**Comment by hrshtv** [comment]
>Shouldn't the discussion be kept for future, say maybe, like before the likely announcement of KSP 2021, people may want to know how it went in 2020.
  
The mods can keep the discussion, it won't get deleted after completion if they don't want to. It's just that they have an option to hide, and delete topics and all posts associated with them if they want to. 
  
>It can be made un-approved so no new post would be of KSP 2020.
  
So are you suggesting a new function to 'archive' the topics?
